/**
 * @file encryption.h
 * 
 * @brief Memory object encryption system
 * 
 * @author
 * Lumi Hyväri <lumi.hyvari@gmail.com>
 * 
 * @copyright
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

#pragma once

/// @brief Security sub-scheme for encrypting memory objects.
typedef struct {
    /// @brief Indicates if feature scheme is enabled
    bool enabled;
    /// @brief Padding generated by certain cryptographical algorithms (usually not the case)
    int size_incremental_difference;
} EncryptionScheme;